trigger:
  - master  # Adjust branch as needed

pool: default


steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'D:\Devop_Agent\1\s\demo\pom.xml'   # Path to your pom.xml
      goals: 'clean install'     # Define Maven goals
      publishJUnitResults: true  # Publish test results
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'   # Change to match your project's Java version
      mavenOptions: '-Xmx1024m'  # Adjust memory if needed
      mavenAuthenticateFeed: false

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/target'
      Contents: '**/*.jar'  # Or .war if it's a web app
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
